export const EXIBIR_LOADING = "EXIBIR_LOADING";
export const ESCONDER_LOADING = "ESCONDER_LOADING";

export const OBTER_DADOS_DASHBOARD = "OBTER_DADOS_DASHBOARD";
export const OBTER_DADOS_DASHBOARD_SUCCESS = "OBTER_DADOS_DASHBOARD_SUCCESS";