export const LOGIN_ESTABELECIMENTO = "LOGIN_ESTABELECIMENTO";
export const LOGIN_ESTABELECIMENTO_SUCCESS = "LOGIN_ESTABELECIMENTO_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";