export const CADASTRAR_ESTABELECIMENTO = "CADASTRAR_ESTABELECIMENTO";
export const CADASTRAR_ESTABELECIMENTO_SUCCESS = "CADASTRAR_ESTABELECIMENTO_SUCCESS";

export const OBTER_ESTABELECIMENTOS = "OBTER_ESTABELECIMENTOS";
export const OBTER_ESTABELECIMENTOS_SUCCESS = "OBTER_ESTABELECIMENTOS_SUCCESS";

export const APROVAR_ESTABELECIMENTO = "APROVAR_ESTABELECIMENTO";
export const APROVAR_ESTABELECIMENTO_SUCCESS = "APROVAR_ESTABELECIMENTO_SUCCESS";

export const REPROVAR_ESTABELECIMENTO = "REPROVAR_ESTABELECIMENTO";
export const REPROVAR_ESTABELECIMENTO_SUCCESS = "REPROVAR_ESTABELECIMENTO_SUCCESS";

export const EXIBIR_MODAL_APROVAR_ESTABELECIMENTO = "EXIBIR_MODAL_APROVAR_ESTABELECIMENTO";
export const ESCONDER_MODAL_APROVAR_ESTABELECIMENTO = "ESCONDER_MODAL_APROVAR_ESTABELECIMENTO";

export const DEFINIR_ESTABELECIMENTO = "DEFINIR_ESTABELECIMENTO";
export const REMOVER_ESTABELECIMENTO = "REMOVER_ESTABELECIMENTO";

export const EXIBIR_MODAL_ALTERACAO_STATUS = "EXIBIR_MODAL_ALTERACAO_STATUS";
export const ESCONDER_MODAL_ALTERACAO_STATUS = "ESCONDER_MODAL_ALTERACAO_STATUS";