export const OBTER_RECOMPENSAS = 'OBTER_RECOMPENSAS';
export const OBTER_RECOMPENSAS_SUCCESS = 'OBTER_RECOMPENSAS_SUCCESS';

export const OBTER_RECOMPENSA = 'OBTER_RECOMPENSA';
export const OBTER_RECOMPENSA_SUCCESS = 'OBTER_RECOMPENSA_SUCCESS';

export const CADASTRAR_RECOMPENSA = 'CADASTRAR_RECOMPENSA';
export const CADASTRAR_RECOMPENSA_SUCCESS = 'CADASTRAR_RECOMPENSA_SUCCESS';

export const ATUALIZAR_RECOMPENSA = 'ATUALIZAR_RECOMPENSA';
export const ATUALIZAR_RECOMPENSA_SUCCESS = 'ATUALIZAR_RECOMPENSA_SUCCESS';

export const EXCLUIR_RECOMPENSA = 'EXCLUIR_RECOMPENSA';
export const EXCLUIR_RECOMPENSA_SUCCESS = 'EXCLUIR_RECOMPENSA_SUCCESS';

export const EXIBIR_MODAL_FORMULARIO_RECOMPENSA = 'EXIBIR_MODAL_FORMULARIO_RECOMPENSA';
export const ESCONDER_MODAL_FORMULARIO_RECOMPENSA = 'ESCONDER_MODAL_FORMULARIO_RECOMPENSA';

export const EXIBIR_MODAL_EXCLUIR_RECOMPENSA = 'EXIBIR_MODAL_EXCLUIR_RECOMPENSA';
export const ESCONDER_MODAL_EXCLUIR_RECOMPENSA = 'ESCONDER_MODAL_EXCLUIR_RECOMPENSA';