export const CADASTRAR_PONTUACAO = "CADASTRAR_PONTUACAO";
export const CADASTRAR_PONTUACAO_SUCCESS = "CADASTRAR_PONTUACAO_SUCCESS";

export const OBTER_PONTUACOES = "OBTER_PONTUACOES";
export const OBTER_PONTUACOES_SUCCESS = "OBTER_PONTUACOES_SUCCESS";